package com.jhairdev.ui_threads;

/**
 *
 * @author Alejandro González Navarro
 */
public class DialogPuntuacion extends javax.swing.JDialog {
    private int posicion;
    private TablaDePuntuacion tablaDePuntuacion;

    /**
     * Creates new form jDialogPuntuacion
     */
    public DialogPuntuacion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        tablaDePuntuacion = new TablaDePuntuacion();
        this.jButtonGuardar.setVisible(false);
        this.jTextFieldNombre.setVisible(false);
        this.jLabelWarning.setVisible(false);
        
    }
    public void iniciar(){
        // Pone los datos
        jLabelPuntuacionC.setText(FormMain.jLabelPuntuacionC.getText());
        jLabelManzanasC.setText(FormMain.jLabelManzanasC.getText());
        jLabelTiempoC.setText(FormMain.jLabelTiempoC.getText());
        jLabelVelocidadC.setText(FormMain.jLabelVelocidadC.getText());
        String[][] string = tablaDePuntuacion.recuperarLista();
        // Si su puntuación es mas alta muestra el botón de guardar
        for (int i = 0; i < 3; i++) {
            if(Integer.parseInt(string[i][1]) <= Integer.parseInt(this.jLabelPuntuacionC.getText())){
                // Al no poder escribir no tiene sentido permitir guardar su nombre.
                //this.jButtonGuardar.setVisible(true);
                //this.jTextFieldNombre.setVisible(true);
                posicion = i;
                break;
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabelPuntuacion = new javax.swing.JLabel();
        jLabelPuntuacionC = new javax.swing.JLabel();
        jLabelManzanas = new javax.swing.JLabel();
        jLabelManzanasC = new javax.swing.JLabel();
        jLabelTiempo = new javax.swing.JLabel();
        jLabelTiempoC = new javax.swing.JLabel();
        jLabelVelocidad = new javax.swing.JLabel();
        jLabelVelocidadC = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jTextFieldNombre = new javax.swing.JTextField();
        jButtonGuardar = new javax.swing.JButton();
        jLabelWarning = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 10, 0};
        layout.rowHeights = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0};
        getContentPane().setLayout(layout);

        jLabelPuntuacion.setText("Puntuación");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 0);
        getContentPane().add(jLabelPuntuacion, gridBagConstraints);

        jLabelPuntuacionC.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        getContentPane().add(jLabelPuntuacionC, gridBagConstraints);

        jLabelManzanas.setText("Manzanas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 0);
        getContentPane().add(jLabelManzanas, gridBagConstraints);

        jLabelManzanasC.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        getContentPane().add(jLabelManzanasC, gridBagConstraints);

        jLabelTiempo.setText("Tiempo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 0);
        getContentPane().add(jLabelTiempo, gridBagConstraints);

        jLabelTiempoC.setText("00:00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        getContentPane().add(jLabelTiempoC, gridBagConstraints);

        jLabelVelocidad.setText("Velocidad");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 0);
        getContentPane().add(jLabelVelocidad, gridBagConstraints);

        jLabelVelocidadC.setText("0/10");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        getContentPane().add(jLabelVelocidadC, gridBagConstraints);

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 0);
        getContentPane().add(jButtonSalir, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 15);
        getContentPane().add(jTextFieldNombre, gridBagConstraints);

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 15);
        getContentPane().add(jButtonGuardar, gridBagConstraints);

        jLabelWarning.setForeground(new java.awt.Color(255, 51, 51));
        jLabelWarning.setText("El nombre debe contener una combinación de 3 letras y números");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 15);
        getContentPane().add(jLabelWarning, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        if(!this.jTextFieldNombre.getText().matches("^[a-zA-Z\\d]{3}$")){
            this.jLabelWarning.setVisible(true);
        } else {
            tablaDePuntuacion.guardarTabla(posicion, this.jTextFieldNombre.getText().toUpperCase(), FormMain.jLabelPuntuacionC.getText());
            this.dispose();
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelManzanas;
    private javax.swing.JLabel jLabelManzanasC;
    private javax.swing.JLabel jLabelPuntuacion;
    private javax.swing.JLabel jLabelPuntuacionC;
    private javax.swing.JLabel jLabelTiempo;
    private javax.swing.JLabel jLabelTiempoC;
    private javax.swing.JLabel jLabelVelocidad;
    private javax.swing.JLabel jLabelVelocidadC;
    private javax.swing.JLabel jLabelWarning;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
